import greenlet

def hello() -> str: ...
def greenlet_switch_to(callable: object) -> object: ...
def greenlet_ping_pong(callable: object, n: int) -> list[object]: ...
def run_hub(workers: list[greenlet.greenlet]) -> list[object]: ...
def hub_run(listen_fd: int, acceptor_fn: object, config: dict[str, int] | None = None) -> None: ...
def green_accept(listen_fd: int) -> int: ...
def green_recv(fd: int, max_bytes: int) -> bytes: ...
def green_send(fd: int, data: bytes) -> int: ...
def hub_stop() -> None: ...
def hub_schedule(g: greenlet.greenlet) -> None: ...
def get_hub_greenlet() -> greenlet.greenlet: ...
def green_close(fd: int) -> None: ...
def http_send_response(
    fd: int,
    status: int,
    headers: list[tuple[bytes, bytes]],
    body: bytes,
) -> int: ...
def green_sleep(seconds: float) -> None: ...
def green_connect(host: str, port: int) -> int: ...
def green_connect_fd(fd: int, host: str, port: int) -> None: ...
def green_poll_fd(fd: int, events: int) -> int: ...
def green_register_fd(fd: int) -> None: ...
def green_unregister_fd(fd: int) -> None: ...
def green_poll_multi(
    fds: list[int], events: list[int], timeout_ms: int
) -> list[tuple[int, int]]: ...
def green_poll_fd_timeout(fd: int, events: int, timeout_ms: int) -> int: ...
def http_read_request(
    fd: int,
    max_header_size: int,
    max_body_size: int,
) -> tuple[str, str, bytes, bool, list[tuple[bytes, bytes]]] | None: ...
